name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ibmg11

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ibmg11roberta3 \
            --source . \
            --region asia-south2 \
            --platform managed \
            --allow-unauthenticated \
            --cpu=4 \
            --memory=8Gi
